version: '3.8'

services:
  liquibase:
    image: liquibase/liquibase
    volumes:
      - ./src/main/resources/db/changelog:/changelog
    command:
      - --changeLogFile=/changelog/changelog.xml
      - --url=jdbc:mysql://db:3307/mydatabase
      - --username=liquibase
      - --password=123456
    depends_on:
      - db

  db:
    image: mysql
    ports:
      - "3307:3307"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: liquibase
      MYSQL_PASSWORD: 123456
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: